# GitHub Labels Configuration
# Based on Issue #337: ラベルの整理と改善
# Managed by ghaction-github-labeler

# Type Labels
- name: "type: bug"
  color: "d73a4a"
  description: "バグの報告"
- name: "type: feature"
  color: "0e8a16"
  description: "新機能の提案"
- name: "type: enhancement"
  color: "a2eeef"
  description: "既存機能の改善"
- name: "type: documentation"
  color: "0075ca"
  description: "ドキュメントの改善"
- name: "type: refactoring"
  color: "5319e7"
  description: "コードのリファクタリング"
- name: "type: performance"
  color: "ff6b6b"
  description: "パフォーマンスの改善"
- name: "type: security"
  color: "ee0701"
  description: "セキュリティ関連の問題"
- name: "type: test"
  color: "bfd4f2"
  description: "テストの追加・修正"

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: "緊急対応が必要な問題"
- name: "priority: high"
  color: "d93f0b"
  description: "優先度が高い問題"
- name: "priority: medium"
  color: "fbca04"
  description: "中程度の優先度"
- name: "priority: low"
  color: "0e8a16"
  description: "優先度が低い問題"

# Status Labels
- name: "status: in progress"
  color: "1d76db"
  description: "作業中"
- name: "status: blocked"
  color: "d73a4a"
  description: "進行がブロックされている"
- name: "status: needs review"
  color: "6f42c1"
  description: "レビュー待ち"
- name: "status: on hold"
  color: "7f8c8d"
  description: "保留中"

# Scope Labels
- name: "scope: frontend"
  color: "c2e0c6"
  description: "フロントエンド関連"
- name: "scope: backend"
  color: "fef2c0"
  description: "バックエンド関連"
- name: "scope: ci/cd"
  color: "bfdadc"
  description: "CI/CD関連"
- name: "scope: tooling"
  color: "e99695"
  description: "開発ツール関連"

# Other Useful Labels
- name: "needs: discussion"
  color: "d4c5f9"
  description: "議論が必要"
- name: "needs: reproduction"
  color: "ffa07a"
  description: "再現手順が必要"
- name: "breaking change"
  color: "b60205"
  description: "破壊的変更を含む"
- name: "good to have"
  color: "84b6eb"
  description: "あると良い改善"

# Special Labels
- name: "dependencies"
  color: "0366d6"
  description: "依存関係の更新"
