# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
chat:
  art: false
language: ja-JP
reviews:
  auto_review:
    ignore_usernames:
      - renovate[bot]
  poem: false
  profile: chill
  request_changes_workflow: true
