# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
chat:
  art: false
language: ja-JP
reviews:
  auto_apply_labels: true
  auto_review:
    ignore_usernames:
      - renovate[bot]
  labeling_instructions:
    - Apply "scope: frontend" label when changes include files in app/** or components/** directories.
    - Apply "scope: backend" label when changes include files in lib/** or app/api/** directories.
    - Apply "scope: ci/cd" label when changes include files in .github/** directory or CI/CD configuration files.
    - Apply "scope: tooling" label when changes include configuration files like biome.json, next.config.ts, tsconfig.json, vitest.config.ts, .coderabbit.yaml, postcss.config.mjs, or components.json.
    - Apply "type: bug" label when PR title or description contains keywords like "fix", "bug", "修正", "バグ", or indicates bug fixes.
    - Apply "type: feature" label when PR title or description contains keywords like "feat", "add", "新機能", "追加", or indicates new features.
    - Apply "type: enhancement" label when PR title or description contains keywords like "improve", "enhance", "改善", or indicates improvements.
    - Apply "type: refactoring" label when PR title or description contains keywords like "refactor", "リファクタリング", or indicates code refactoring.
    - Apply "type: test" label when changes include test files (**/__tests__/**, test/**, *.test.ts, *.test.tsx, *.spec.ts, *.spec.tsx).
    - Apply "type: documentation" label when changes include documentation files (**/*.md, docs/**) or when PR title contains "docs".
    - Apply "type: performance" label when PR title or description contains keywords like "perf", "performance", "optimize", "パフォーマンス", "最適化".
    - Apply "type: security" label when PR title or description contains keywords like "security", "vulnerability", "CVE", "セキュリティ", "脆弱性".
    - Apply "dependencies" label when changes include package.json, pnpm-lock.yaml, or other dependency management files.
    - Apply "breaking change" label when PR title or description contains keywords like "breaking", "BREAKING CHANGE", "破壊的", or indicates breaking changes.
  path_instructions:
    - instructions: |
        各指摘コメントの冒頭には、必ずPull Requestの作成者（Author）へのメンションを含めてください。

        【メンションのルール】
        1. Authorが "copilot", "copilot[bot]", またはその他のCopilot関連のBotであると判断できる場合:
           必ず "@copilot" とメンションしてください。
        2. それ以外（人間のユーザー）の場合:
           Authorの正しいユーザー名（例: @username）をメンションしてください。

        形式例:
        "@copilot ここは修正が必要です..."
        "@user123 提案ですが..."

        理由:
        コメントの通知漏れを防ぐため、例外なくメンションが必要です。
      path: "**/*"
    - instructions: |
        これらのファイルは shadcn/ui によって生成されたUIコンポーネントです。

        以下のルールに従ってレビューしてください：
        1. **重大なバグ**や**セキュリティ上の脆弱性**が見つかった場合のみ指摘してください。
        2. コードスタイル、型定義の厳密化、軽微なリファクタリング提案は**行わないでください**。
        3. もし指摘する場合は、それがshadcn/uiの標準実装から逸脱するリスクがないか考慮してください。
      path: "components/ui/**/*.tsx"
    - instructions: |
        このファイルは Supabase CLI によって自動生成された型定義ファイルです。

        以下のルールに従ってレビューしてください：
        1. **レビュー対象外**とし、指摘は行わないでください。
        2. 機械生成されたファイルのため、コードスタイルや型定義の指摘は不要です。
        3. もし問題がある場合は、データベーススキーマまたは生成コマンドの修正を提案してください。
      path: "types/supabase.ts"
  poem: false
  profile: chill
  request_changes_workflow: true
