name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          github-token: ${{ github.token }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
